Repository Sintrop/core-contracts, pull requests merged in 2022-07, with the labels that each got.

#89 feat: configure callable in isapool with category
  migrations/2_deploy_contracts.js
Labels: done

#99 add specs to acess producer fields
  CHANGELOG.md
  test/ProducerContract.test.js
Labels: spec

#102 pp-issue-79-add-investors
  CHANGELOG.md
  contracts/InvestorContract.sol
  contracts/types/InvestorTypes.sol
  test/InvestorContract.test.js
Labels: new feature, version 2.0
