Repository Sintrop/core-contracts, pull requests merged in 2022-06, with the labels that each got.

#57 Updates inspectionType.sol (enum & struct)
  contracts/Sintrop.sol
  contracts/types/InspectionTypes.sol
  package.json
  test/Sintrop.test.js
Labels: refact, new feature

#58 test: add context to activist spec
  test/ActivistContract.test.js
Labels: spec, refact

#67 feat: add a chnagelog file
  CHANGELOG.md
Labels: new feature

#54 feat: add a blockable contract to manage blocks
  CHANGELOG.md
  contracts/Blockable.sol
  contracts/DeveloperPool.sol
  test/Blockable.test.js
  test/DeveloperPool.test.js
Labels: refact

#80 creation of ContributorsContract
  CHANGELOG.md
  contracts/ContributorContract.sol
  contracts/types/ContributorTypes.sol
  test/ContributorContract.test.js
Labels: in progress, new feature

#83 #61 Add specs to activist fields
  test/ActivistContract.test.js
Labels: spec

#82 Evr 46 time between inspections
  CHANGELOG.md
  contracts/ProducerContract.sol
  contracts/Sintrop.sol
  contracts/types/InspectionTypes.sol
  contracts/types/ProducerTypes.sol
  migrations/2_deploy_contracts.js
  test/ProducerContract.test.js
  test/Sintrop.test.js
Labels: new feature
